### ISSUE TITLE
using summary writer on GPU 0 only will give loss only of that GPU ?

### ISSUE THREAD

**Issue by aakash-saboo** [spellrun/spell-deeplab-voc-2012#2]
Hi.
 In the distributed horovod example, you are writing to tensorboard only when GPU=0.
Can you tell if it is fully correct or not?
When GPU is 0, you will only write the loss on that GPU only and NOT the average loss of all GPUs.
This means that the loss we are plotting correspond to loss computed using a batch = batch_size/num_of_gpus .
Dont you think its incorrect?

If I want the average loss of all GPUs, how can i do it?

Thanks in advance.

**Comment by ResidentMario** [comment]
You are correct that logging only when GPU=0 only gives you the metrics values for that GPU's batch chunk.

However, you have to look at logging the metrics for a single model instead of for all of them as a performance optimization.

If you are running on a distributed GPU cluster (e.g. the GPUs are not all located on the same machine), there is network overhead to synchronizing data across the machines. If we average pool the metric value across all of the GPUs every time we log to Tensorboard, we incur that cost.

If we instead track the metric based on just one batch chunk, assuming that batch chunk is a reasonable estimate of the batch as a whole, no network roundtrips are necessary, speeding up model training.

To log the metric for the whole batch, use [horovod.torch.allreduce](https://horovod.readthedocs.io/en/stable/api.html#horovod.torch.allreduce).

[You may also be interested in some further performance tips here](https://www.reddit.com/r/MachineLearning/comments/hmgr9g/d_pytorch_distributeddataparallel_and_horovod/fx7m804/). Happy training!

**Comment by aakash-saboo** [comment]
Hey!
thanks for your quick response and the attached link!
Appreciate your help a lot!!!!
